name: Build, Test, and Deploy Unity Project

on: [push, pull_request]

jobs:

  # Job to run Playmode tests
  runPlaymodeTests:
    name: Run Playmode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-PlaymodeTests-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-PlaymodeTests-
            Library-

      - name: Run Unity Playmode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.3.6f1
          testMode: PlayMode
          # The path where test results will be generated
          artifactsPath: artifacts/TestResults/Playmode

      - name: Upload Playmode Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Playmode-Test-Results
          path: artifacts/TestResults/Playmode